sonar.projectKey=justinfowler5_kepler_exoplanet_ml
sonar.organization=justinfowler5
sonar.projectName=Kepler Exoplanet Classification Engine
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Exclude generated / local stack noise from analysis
sonar.exclusions=**/.venv/**,**/.local-stack/**,**/mlruns/**,**/__pycache__/**,**/htmlcov/**
sonar.coverage.exclusions=**/tests/**
sonar.test.inclusions=tests/**/*.py
